services:
  kemono-downloader:
    image: lanusgaming/kemono-downloader:preview
    build: ./
    container_name: kemono-downloader
    env_file:
      - .env
    volumes:
      - ./temp:/temp
      - ./data:/data
      - ./config:/config
