services:
  kemono-downloader:
    image: git.patrick-dev.net/patrick/kemono-downloader:latest
    build: ./
    container_name: kemono-downloader
    env_file:
      - .env
    volumes:
      - ./temp:/temp
      - ./data:/data
      - ./config:/config
