services:
  kemono-downloader:
    image: lanusgaming/kemono-downloader:preview
    build: ./
    container_name: kemono-downloader
    environment:
      - SESSION_COOKIE=
      - CREATOR_URL_FILE=
    volumes:
      - ./temp:/temp
      - ./data:/data
      - ./config:/config
